### ISSUE TITLE
Retrieve candidates from other functions

### ISSUE THREAD

**Issue by alphapapa** [cyrus-and/comb#1]
ISTM that this package could be very useful for MELPA maintainers reviewing new packages.  Submitters are told to run `package-lint` and `checkdoc`, but there are often some false positives or exceptions to the issues it flags.  Comb could help by listing the issues found and letting reviewers mark them, rather than keeping track manually or mentally.  Its export function could even let developers and reviewers upload saved annotations to a pull request.

However, since Comb only lists items by regexp searches, this isn't possible.

What if Comb could also retrieve a list of items by calling functions?

**Comment by cyrus-and** [comment]
That's a neat idea, so let's say each entry of the pattern could also be a function which takes one parameter (the filename) and returns a sequence of ranges `(BEGIN . END)`?

The problem with using Comb as a tool for code review on *live* repositories is that the annotations are identified by filename + match range, so a change in one file will break all the following annotations in the same file. This, in your scenario, means that every time a submitter changes something maintainers should start over with a new review, which in principle it may be reasonable since one would expect that prior issues are resolved...

**Comment by alphapapa** [comment]
> That's a neat idea, so let's say each entry of the pattern could also be a function which takes one parameter (the filename) and returns a sequence of ranges (BEGIN . END)?

Seems reasonable to me.

> The problem with using Comb as a tool for code review on live repositories is that the annotations are identified by filename + match range, so a change in one file will break all the following annotations in the same file.

Perhaps exports could use literal strings instead of ranges.  It wouldn't be perfect, of course, because the strings wouldn't necessarily be unique.  I guess you could get fancy and also include the position, and then search around that position for the match.  On the other hand...

> This, in your scenario, means that every time a submitter changes something maintainers should start over with a new review, which in principle it may be reasonable since one would expect that prior issues are resolved...

That seems reasonable to me.

**Comment by cyrus-and** [comment]
> Perhaps exports could use literal strings instead of ranges. It wouldn't be perfect, of course, because the strings wouldn't necessarily be unique. I guess you could get fancy and also include the position, and then search around that position for the match. On the other hand...

Yep, still not a silver bullet though... I guess I'll just dismiss this as "not the intended use case" for now.

> That's a neat idea, so let's say each entry of the pattern could also be a function which takes one parameter (the filename) and returns a sequence of ranges (BEGIN . END)?

~Implemented in the [callbacks][1] branch, feel free to give it a try.~

Merged into master.

[1]: https://github.com/cyrus-and/comb/tree/callbacks

**Comment by cyrus-and** [comment]
Even better, since 5096ce366f71f884d1d3e9a4c246d3b545fbd1d1 callbacks accept a filename and a buffer so there's no need to read the file twice if needed by the callback.

**Comment by cyrus-and** [comment]
> Implemented in the callbacks branch, feel free to give it a try.

Merged into master, thanks for this idea.
