### ISSUE TITLE
NOT lookups

### ISSUE THREAD

**Issue by avkoval** [cyrus-and/comb#2]
Hi,

its just a question, would it be hard or not to include possibility to exclude some some lines with specific regexps?

So, searching for:

    <term1> but NOT <term2> in same line?

**Comment by cyrus-and** [comment]
I'm not sure I'm understanding correctly but I guess you can almost always structure your [regexp](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regular-Expressions.html) to explicitly rule out what you don't want. But you have to consider that regexps are good at matching not excluding...

Can you provide a real-world use case for this?
