### ISSUE TITLE
Suggestion: Enhance discoverability of package description

### ISSUE THREAD

**Issue by alphapapa** [cyrus-and/comb#3]
Hi,

I was replying to a Reddit comment in which someone mentioned using code review tools in Emacs, and I remembered this package and wanted to share it, but I couldn't remember the name of it.  So I searched MELPA for "audit" and "review" and some other terms, but I couldn't find it.  Finally I used a thesaurus to find other search terms related to "audit," and then I found this package by searching MELPA for "analysis".

Maybe it's just me, but when thinking of this package, I thought of auditing and reviewing code, so that's what I searched for, but it didn't lead me here.

So, FYI, you might want to adjust the package description to make it more discoverable.  I'm guessing that people who would use it aren't able to find it because they aren't thinking in terms of "manual static analysis."  :)  To put it another way, I don't think "manual static analysis" implies "a native Emacs Lisp solution to search, browse and annotate occurrences of regular expressions in files," which is a much more helpful description.

I hate to suggest a "word dump," but I think more keywords are needed to help users discover it.  Here's my best suggestion at the moment: "Annotate, analyze, audit, and review code interactively".

**Comment by cyrus-and** [comment]
You're probably right, the fact is that it al started from a *security analysis* use case. Let me see what I can come up with...

**Comment by alphapapa** [comment]
BTW, I just added it to https://github.com/alphapapa/emacs-package-dev-handbook#auditing--reviewing, to help me remember it, at least.  :)

**Comment by cyrus-and** [comment]
Thank you so much! ^_^

**Comment by cyrus-and** [comment]
I think that the two most important keywords are *audit* and *grep*, so:

> Interactive code auditing and grep tool
